khriztianmoreno/fullstack-js-makeitreal

maria_sirley/README.md
revisión de pequeña descripción
=> add new member - Cristian Moreno

Juan_Pablo_Acosta/README.md
Add new member with description
=> Add new member Juan Acosta

DanielaCalle/README.md
The commit contains a new file with a short description of Daniela Calle
=> Add new member - Daniela Calle

daniel_alvarez/readme.md
Hello, please checkout my profile pull request
=> Add member credentials - Daniel Alvarez

README.md
Summit with README.md file modified with Daniela Calle's information in line 13 according with the homework.
=> README.md File modified

README.md
=> Registro de datos en README.md

README.md
modificacion del archivo Readmi
=> Mariasirley tg

README.md
I'm addind a new member person. The information is about myself.
=> Add information in participants

README.md
conflict corrected, new member added
=> New member added to README.md file

README.md
Primera tarea de añadir info al README
=> Add Bria info to README

cristian_moreno/html_1/index.html
Create a new file to show the basic tags
=> Create basic html file - Cristian Moreno

isabella_serna/html_1/data.html
=> html - asignacion #1

arley_gil/html/index.html
Tarea de realizar un archivo html designada por el tutor para saber en que nivel nos encontramos de esta herramienta.
=> tarea html

arley_gil/html/index.html, arley_gil/web_semantica/semantica.html
Cristian en este pull podras encontrar los dos archivos html que nos mandaste a realizar uno es el de classroom y el otro el que tu nos sugeriste hacer para validar el nivel en que nos encontramos por HTML.
Gracias por tu amable atención.
=> Tarea de archivos html

brianith_navarro/web_semantica/index.html
=> Add first web semantica

maria_sirley/html_1/index.html
Hola Profe,
Estas son las etiquetas en html que me se, no le anexe hojas  de estilo por que usted solo nos pidio las etiquetas de html, aun que se que style es una etiqueta de html no es una buena practica declarar los estilos en el index, si no crear un archivo diferente, para luego linkearlo en en el index.
=> Mi primer html

Juan_Lopera/ReadMe.md, Juan_Lopera/Tim/index1.html, Juan_Lopera/index.html, Juan_Lopera/styles.css, README.md
Tarde pero lo hice escuchando arley
=> Juan lopera

DanielaCalle/tim_html/index.html, DanielaCalle/web_semantica/css/styles.css, DanielaCalle/web_semantica/index.html
Submit the challenge of Tim Berners-Lee by Dani Calle
=> Daniela's tim challenge

cristopher_rojas/tim_berners/index.html
=> tim berners ejercicio

lauramos/tim_berners/index.html
=> Tim Berners-Lee biography

cristopher_rojas/web_semantica/index.html
=> web semantica

laura_monsalve/TimBerners/index.html
Teacher Khriztian solicited create a new file HTML where I give information about Tim Berners life.
=> Laura monsalve tim berners challenge

arley_gil/tim_bernerns/index.html, arley_gil/web_semantica/semantica.html
=> Arley tim bernerns example

maria_sirley/Tim Berners/index.html
Hola 
Presento el segundo ejercicio de HTML con las pautas que se dieron en clase 
Cordial saludo, Quedo atenta.
=> maria_M_Tim_Berners-Lee

isabella_serna/js-hello-world/alert.js, isabella_serna/js-hello-world/index.html
Create scripts for hello world message
=> create hello world in js

cristopher_rojas/js-hello-world/alert.js, cristopher_rojas/js-hello-world/index.html, cristopher_rojas/tim_berners/index.html
=> Alerta JS Hello javaScripters!

arley_gil/js-helloworld/alert.js, arley_gil/js-helloworld/index.html
Cristian este pull es del ejecicio hola mundo con javascritp.
=> Javascript hellow world arley

alejandro_becerra/hello_world_js/hello_world.js, alejandro_becerra/hello_world_js/index.html
=> hello world js

laura_vdearmas/js-helloworld/alert.js, laura_vdearmas/js-helloworld/index.html
Ejercicio 1 y 2 de la clase JS
=> Laurav js hello world

maria_sirley/js/alert.js, maria_sirley/js/maria_hello_word_js.index.html
para aprobación del mensaje que hemos realizado en clases utilizando las etiquetas <script></script>
=> Maria_hello_word

maria_sirley/js-variables/maria_variables.html, maria_sirley/js-variables/trabajando_variables.js
-crear una variable
-dando el nombre correcto a una variable y explicando el por que de la variable en commits en el codigo
=> Maria variable js

Juan_Pablo_Acosta/JavaScript/variables/dandoElNombreCorrecto.js, Juan_Pablo_Acosta/JavaScript/variables/index.html, Juan_Pablo_Acosta/JavaScript/variables/script.js
Ejercicios de JavaScript realizados en clase
=> Juan acosta variables js

Juan_Pablo_Acosta/Reto/index2.html, Juan_Pablo_Acosta/Reto/style2.css
CSS and HTML updated with section aboutme
=> About me section added

diana_rojas/js-hello-world/alert.js, diana_rojas/js-hello-world/index.html
Ejercicios de ventana de alerta desde un archivo .html y desde un archivo .js
=> Diana js hello world

cristopher_rojas/js-variables/dandoElNombreCorrecto.js, cristopher_rojas/js-variables/trabajandoConVariables.js
Exercise "Working with variables", on JS
=> Cristopher variables js

monica_gonzalez/js-variables/DandoElNombreCorrecto.js, monica_gonzalez/js-variables/TrabajandoConVariables.js, monica_gonzalez/js-variables/index.html
Ejercicios de declaración de variables
=> Monik variables js

arley_gil/js-helloworld/alert.js, arley_gil/js-helloworld/index.html, arley_gil/js-variables/arley-variables2.html, arley_gil/js-variables/arley-variales.html, arley_gil/js-variables/arley.js, arley_gil/js-variables/arley2.js
Kriztian este es el primer ejecicio de variables
=> fist exercise

diana_rojas/js-variables/dandoElNombreCorrecto.js, diana_rojas/js-variables/index.html, diana_rojas/js-variables/trabajandoConVariables.js
Ejercicios de declaración de variables y como nombrar una variable
=> Diana variables js

lauramos/js-variables/dandoElNombreCorrecto.js, lauramos/js-variables/index.html, lauramos/js-variables/trabajandoConvariables.js
Variables naming convention exercises
=> Lauramos variables js (naming convention exercise)

isabella_serna/js-variables/dandoElNombreCorrecto.js, isabella_serna/js-variables/index.html, isabella_serna/js-variables/trabajandoConVariables.js
Practice about variables with let and const
=> Isabella variables js

laura_vdearmas/js-variables/index.html, laura_vdearmas/js-variables/planeta.js, laura_vdearmas/js-variables/trabajandoconvariables.js
=> Laurav variables js

cristian_moreno/html_1/index.js, cristian_moreno/html_1/math.js, cristian_moreno/js-variables/dandoElNombreCorrecto.js, cristian_moreno/js-variables/index.html, cristian_moreno/js-variables/trabajandoConVariables.js
- Trabajando con variables
- Dando el nombre correcto
=> Ejercicio de variables JS

brianith_navarro/js-variables/dandoElNombreCorrecto.js, brianith_navarro/js-variables/index.html, brianith_navarro/js-variables/trabajandoConVariables.js, brianith_navarro/js-variables/trabajoConVariables.html
Primer Pull request del Primer ejercicio con JS
=> PrimerEjercicioConJS

alejandro_becerra/template_string/index.html, alejandro_becerra/template_string/script.js
added exercise for string templates with printing both in console and in the page using console.log and alert
=> Strings template exercise

isabella_serna/template_string/index.html, isabella_serna/template_string/template_string.js
First exercise with template strings
=> First exercise with template strings

laura_vdearmas/templatestring/index.html, laura_vdearmas/templatestring/template.js
=> Ejercicio de Template String

arley_gil/templateString/arley.js, arley_gil/templateString/index.html
Cristian este es el pull request del ejercicio de string.
=> Arley Sting Exercise

maria_sirley/templateString/template.html, maria_sirley/templateString/template.js
-utilizando concatenación de cadenas o string ``  y en ella pasando variables `${}`
=> maria_Templete.Js

lauramos/templateString/index.html, lauramos/templateString/templateString.js
Use templates strings to concatenate variables
=> Template string Laura Ramos

diana_rojas/templateString/index.html, diana_rojas/templateString/templatestring.js
Solución de ejercicio propuesto en clase de template string
=> Exercise template string Diana

laura_monsalve/jsVariables/templateString/professionalProfile.js
Here, you can see my professional information. Iám using a template string
=> Add information about my professional profile

alejandro_becerra/node_server/.gitignore, alejandro_becerra/node_server/index.js, alejandro_becerra/node_server/package-lock.json, alejandro_becerra/node_server/package.json
=> Alejandro node server

laura_monsalve/jsHello-world/index.html, laura_monsalve/jsVariables/dandoElNombreCorrecto, laura_monsalve/jsVariables/index.html, laura_monsalve/jsVariables/variable.js
In this Pr, you can see de excercise about varibales whit JS.
The JS file's is whit console.log
=> add new files for variables in JS

cristopher_rojas/corregir-la-adicion/app.js, cristopher_rojas/corregir-la-adicion/index.html, cristopher_rojas/el-nombre-de-javascript/app.js, cristopher_rojas/el-nombre-de-javascript/index.html, cristopher_rojas/muestre-el-signo/app.js, cristopher_rojas/muestre-el-signo/index.html, cristopher_rojas/reescribiendo-if/app.js, cristopher_rojas/reescribiendo-if/index.html, cristopher_rojas/switches/app.js, cristopher_rojas/switches/index.html
Estimado, subo todos los ejercicios realizados el 27-01-2021 sobre condicionales
=> Ejercicios Condicionales 

alejandro_becerra/if_to_switch/index.html, alejandro_becerra/if_to_switch/script.js, alejandro_becerra/js_name/index.html, alejandro_becerra/js_name/script.js, alejandro_becerra/num_compare/index.html, alejandro_becerra/num_compare/script.js, alejandro_becerra/numbers/index.html, alejandro_becerra/numbers/script.js, alejandro_becerra/switch_to_if/index.html, alejandro_becerra/switch_to_if/script.js, alejandro_becerra/template_string/script.js, alejandro_becerra/tertiary_operands/index.html, alejandro_becerra/tertiary_operands/script.js
@khriztianmoreno I did not manage to make the last exercise work.
=> Alejandro nums strings

isabella_serna/operations/index.html, isabella_serna/operations/operation.js
=> operations subject

Juan_Lopera/ReadMe.md, README.md
Learn & practice again the flow for Git and Github
=> Add new 07032021
